console.log(crazyVariable);
crazyVariable = "Esto es de locos!";
console.log(crazyVariable);
crazyVariable = 666;
console.log(crazyVariable);
crazyVariable = Infinity;
console.log(crazyVariable);
let crazyVariable = NaN;
console.log(crazyVariable);
crazyVariable = false;
console.log(crazyVariable);
let crazyVariable = undefined;
console.log(crazyVariable);
