let sideA = +prompt("Dame un lado del triangulo: ");
let total = sideA;
let greater = sideA;
let sibeB = +prompt("Dame otro lado del triangulo: ");
total = total + sibeB;
greater = greater > sibeB ? greater : sibeB;
let sideC = +prompt("Dame el último lado del triangulo: ");
total = total + sideC;
greater = greater > sideC ? greater : sideC;
let isTriangle = total - greater > greater;
let msgAnswer = "Los lados " + sideA + ", " + sibeB + ", " + sideC + " " + (isTriangle ? "SI" : "NO");
let equilateral = sideA == sibeB && sibeB == sideC ? "equilateralo" : "";
let isosceles = sideA == sibeB || sibeB == sideC ? "isosceles" : "";
let scalene = sideA != sibeB && sibeB != sideC && sideC != sideA ? "scaleno" : "";
let msgType = equilateral !== "" ? equilateral : isosceles;
msgType = scalene !== "" ? scalene : msgType;
msgType = isTriangle ? "de tipo " + msgType : "";
console.log(msgAnswer + " forman un triangulo " + msgType);
